### ISSUE TITLE
Pretrained Checkpoint

### ISSUE THREAD

**Issue by Coice** [bfs18/e2_tts#1]
I'm not sure if I missed it, but do you have a pre-trained checkpoint of LJSpeech available to test inference? I only see the vocoder model. Thanks!

**Comment by bfs18** [comment]
Hi @Coice Thanks for your interest. The trained checkpoint for LJSpeech will be uploaded shortly.

**Comment by bfs18** [comment]
Hi @Coice If you are eager to see the results, you can try this [checkpoint](https://drive.google.com/file/d/1QASey2jNFGUIluv1Gt9bUOeWgwH-i5hm/view?usp=sharing), which has run for 500k steps. [Here](https://drive.google.com/file/d/1plSXXMCOFlSBoMbKR7nAs0ramtxjTFKw/view?usp=sharing) is the test result.

**Comment by shaun95** [comment]
> Hi @Coice If you are eager to see the results, you can try this [checkpoint](https://drive.google.com/file/d/1QASey2jNFGUIluv1Gt9bUOeWgwH-i5hm/view?usp=sharing), which has run for 500k steps. [Here](https://drive.google.com/file/d/1plSXXMCOFlSBoMbKR7nAs0ramtxjTFKw/view?usp=sharing) is the test result.

Thank you for your great work and thorough investigation.

I have a minor observation: the samples from the 500k steps checkpoint seem to have a lower pitch for the LJ speaker. Initially, I suspected this might be due to 24 kHz Wav samples being played at a lower rate of 22.05 kHz, but that doesn’t appear to be the case.

Interestingly, the earlier samples you shared here , https://github.com/lucidrains/e2-tts-pytorch/issues/25#issuecomment-2295214139 sound better to me (pitch-wise). Perhaps the 500k model might improve with additional training?

**Comment by bfs18** [comment]
hi @shaun95 I realized there was a sampling rate mismatch between the acoustic model and the vocoder, so I updated the e2_tts.yaml file accordingly. The earlier samples were synthesized by a model trained for 1000k steps without any sampling rate mismatch, so they are of better quality.

**Comment by bfs18** [comment]
@Coice  Uploaded a new checkpoint.

**Comment by Coice** [comment]
Thank you! I'll close this issue.
