### ISSUE TITLE
did you train this model without using alignments ?

### ISSUE THREAD

**Issue by manmay-nakhashi** [bfs18/e2_tts#2]

**Comment by manmay-nakhashi** [comment]
is alignment_dir in build_filelist is phoneset dir ?

**Comment by bfs18** [comment]
Hi @manmay-nakhashi No alignment is used; the term is simply a legacy name. The alignment_dir refers to the directory that contains the transcribed phoneme files generated by build_ljspeech.py.

**Comment by honghee99** [comment]
This is excellent work.I noticed that you also used duration loss in your training. I would like to ask if it's possible for the model to learn alignment without using duration loss?

**Comment by bfs18** [comment]
Hi @honghee99 The duration model actually predicts the ratio of num_frames to num_tokens. This ratio is used to determine the number of Mel frames from the number of phonemes.

**Comment by honghee99** [comment]
I'm encountering an error when running on a single GPU: 'DataLoader worker (pid xxx) is killed by signal.' I've read that this might be due to multiprocessing issues, but even after setting num_workers to 1, the problem persists. Could you share how many GPUs you're using and what your num_workers setting is?

**Comment by bfs18** [comment]
@honghee99 I am able to run the program using the default configuration. However, enabling the [dataset cache](https://github.com/bfs18/e2_tts/blob/e73f124c59337cbb1aaf6fd7fa8f062d6900af2a/rfwave/dataset.py#L46) might lead to the error you mentioned.

**Comment by honghee99** [comment]
The error mentioned above is caused by the torchaudio.load() module. When I use version 2.2.0, it results in a segmentation fault, but it runs normally with version 2.0.2. However, using version 2.0.2 requires changing the torch version to 2.0.2 as well, which is incompatible with your code. Online sources suggest that this might be due to an incorrect CUDA version or ffmpeg version. Could you please let me know your CUDA and ffmpeg versions?

**Comment by honghee99** [comment]
The error is caused by torchaudio.load. It works fine with version 2.0.2 but gives a segmentation fault in 2.2.0. However, using torchaudio 2.0.2 requires downgrading torch to 2.0.2, which isn't compatible with your code. It might be related to CUDA or ffmpeg versions. Could you share your CUDA and ffmpeg versions?

**Comment by bfs18** [comment]
@honghee99 The issue might also be related to the Python version. I recommend using Python 3.10 or 3.11 to ensure compatibility. CUDA is installed as part of the PyTorch 2.2.0 prerequisites, and the version being used is 12.1.

**Comment by honghee99** [comment]
I was able to run your code successfully using torch 2.0.0, torchaudio 2.0.0, and pytorch-lightning 2.0.0. Now I've run into another issue. When I try to use the checkpoint you provided for inference, I’m getting this error.
```
Traceback(most recent call last):
    File "/ssd1/2hl/tts/e2e/e2_tts-main/inference.py", line 238, in <module>
        tts(args.aco_model_dir, args.voc_model_dir, text_lines, ref_audio, ref_text, phone2id, args.save_dir, sr=args.sr)
    File "/ssd1/2hl/tts/e2e/e2_tts-main/inference.py", line 205, in tts
        audio_hat = voc_exp.reflow.sample_ode(mel_hat, N=10)[-1]
    File "/ssd1/2hl/tts/e2e/e2_tts-main/rfwave/experiment_reflow_subband.py", line 282, in sample_ode
        traj_f= self.sample_ode_subband(
    File " /home/2hl/anaconda3/envs/e2tts/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args,**kwargs)
    File "/ssd1/2hl/tts/e2e/e2_tts-main/rfwave/experiment_reflow_subband.py", line 210, in sample_ode_subband
        z0 = self.get_joint_z0(mel)# get z0 must be called before pre-processing mel
    File "/ssd1/2hl/tts/e2e/e2_tts-main/rfwave/experiment_reflow_subband.py", line 127, in get_joint_z0
        z0 = self.get_joint_subband(rf)
    File "/ssd1/2hl/tts/e2e/e2_tts-main/rfwave/experiment_reflow_subband.py", line 81, in get_joint_subband
        S =F.pad(S,(0,0,0,0, self.left_overlap, self.right_overlap - 1),mode='circular')
    RuntimeError: Invalid padding_size, expected 4 but got 6
```

**Comment by bfs18** [comment]
@honghee99 
comment this line 
https://github.com/bfs18/e2_tts/blob/2a3c19259aac46ff050de818a2947dd487f3772f/rfwave/experiment_reflow_subband.py#L81
and use the following line instead.
https://github.com/bfs18/e2_tts/blob/2a3c19259aac46ff050de818a2947dd487f3772f/rfwave/experiment_reflow_subband.py#L83

**Comment by honghee99** [comment]
Thank you！😃

**Comment by JohnHerry** [comment]
> Hi @honghee99 The duration model actually predicts the ratio of num_frames to num_tokens. This ratio is used to determine the number of Mel frames from the number of phonemes.

can this prediction imporoved by adding speaker condition [or prompt condition]?
